openapi: 3.0.2
info:
  title: 'Simple social network'
  version: '1.0'
paths:
  /api/posts:
    get:
      operationId: listPosts
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        text:
                          type: string
                        author:
                          type: string
                          readOnly: true
                        created:
                          type: string
                          format: date-time
                          readOnly: true
                        likes_num:
                          type: string
                          readOnly: true
                      required:
                      - text
          description: ''
    post:
      operationId: CreatePost
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                text:
                  type: string
              required:
              - text
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  text:
                    type: string
                  author:
                    type: string
                    readOnly: true
                  created:
                    type: string
                    format: date-time
                    readOnly: true
                  likes_num:
                    type: string
                    readOnly: true
                required:
                - text
          description: ''
  /api/login:
    post:
      operationId: CreateJWT
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
                  writeOnly: true
              required:
              - email
              - password
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  email:
                    type: string
                required:
                - email
          description: ''
  /api/signup:
    post:
      operationId: CreateUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                username:
                  type: string
                  maxLength: 255
                password:
                  type: string
                  writeOnly: true
                  maxLength: 128
                  minLength: 8
              required:
              - email
              - username
              - password
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    format: email
                    maxLength: 255
                  username:
                    type: string
                    maxLength: 255
                  date_joined:
                    type: string
                    format: date-time
                    readOnly: true
                required:
                - email
                - username
          description: ''
  /api/posts/{id}/like:
    post:
      operationId: CreateLike
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  profile:
                    type: string
                    readOnly: true
                  post:
                    type: string
                    readOnly: true
                  time:
                    type: string
                    readOnly: true
          description: ''
  /api/posts/{id}/unlike:
    post:
      operationId: CreateLike
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties: {}
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  profile:
                    type: string
                    readOnly: true
                  post:
                    type: string
                    readOnly: true
                  time:
                    type: string
                    readOnly: true
          description: ''
